### ISSUE TITLE
LaravelFivePackageBridgeTrait.php on line 63 

### ISSUE THREAD

**Issue by ghost** [morrislaptop/LaravelFivePackageBridges#1]
[RuntimeException]  
  Error Output: PHP Fatal error:  Call to undefined method Illuminate\Config\Repository::package() in /home/nelson/testing/tests/vendor/morrislaptop/laravel-five-package-bridges/src/LaravelFivePackageBridgeTrait.php on line 63

**Comment by morrislaptop** [comment]
Hi Tecktok,

Did you add the following service provider into you config/app.php?

'Morrislaptop\LaravelFivePackageBridges\ConfigServiceProvider',

It probably has to go above any third party packages.. 

What package are you bringing in?

Cheers,
Craig

**Comment by ghost** [comment]
yes, i'm sorry, i didn't add the service provider when i see the error

2015-01-22 3:20 GMT-05:00 Craig Morris notifications@github.com:

> Hi Tecktok,
> 
> Did you add the following service provider into you config/app.php?
> 
> 'Morrislaptop\LaravelFivePackageBridges\ConfigServiceProvider',
> 
> It probably has to go above any third party packages..
> 
> What package are you bringing in?
> 
> Cheers,
> Craig
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/morrislaptop/LaravelFivePackageBridges/issues/1#issuecomment-70985817
> .

## 

Cordialmente:

_Nelson Alberto Arbeláez Echeverri_
Tel: 036-8906069il  Cel: 3178850415
E-mail: nealarec@gmail.com , naarbelaez0@misena.edu.co
