### ISSUE TITLE
Add 'replace' composer tip

### ISSUE THREAD

**Issue by younes0** [morrislaptop/LaravelFivePackageBridges#7]
Very nice lib dude
Problem with 4.x packages is that most of their composer file requires laravel 4.x support package.
Adding this solves this issue:

``` json
"replace": {
    "illuminate/support": "4.2.8"
},
```

why not adding this little tip in your README?

**Comment by morrislaptop** [comment]
Oh nice, could I put that in my composer.json?

**Comment by younes0** [comment]
You mean in the lib's composer.json? That makes sense! Please let me know if it works, so the lib's users wouldn't have to add it themselves

**Comment by younes0** [comment]
my bad: latest 4.x support version is 4.2.17

``` json
"replace": {
    "illuminate/support": "4.2.17"
},
```

**Comment by morrislaptop** [comment]
I'll try it out, I think because I require laravel/framework ~5.0 it will
bring in the illuminate/support files so I should be able to put it in my
composer.json without harm... I'm just about to head away for the weekend
so will try early next week

**Comment by morrislaptop** [comment]
Looks to work for me! I put the version constraint as ~4.2 so it should cover all all support releases into the future.

**Comment by younes0** [comment]
yes: I could 'replace' from my app's composer where 4.x laravel are declared.
cheers.
