### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by alirezarahmani** [morrislaptop/LaravelFivePackageBridges#8]
@morrislaptop  How did you add your package to composer , that make you able to use this command for installation `composer require morrislaptop/laravel-five-package-bridges`?

**Comment by morrislaptop** [comment]
What do you mean you just run it from the command line? You need to install composer globally

**Comment by alirezarahmani** [comment]
@morrislaptop i've create L5 package but i cannot add it to package list?

**Comment by morrislaptop** [comment]
What is the error are you getting?

**Comment by alirezarahmani** [comment]
@morrislaptop I just try to add my package to packagist , it says to me, you should have the vonder folder?

**Comment by morrislaptop** [comment]
Sooooo is this anything to do with my bridging package?

**Comment by alirezarahmani** [comment]
@morrislaptop not your package; my own , i mean how you add your package to packagist ?
