### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by googledrummer** [morrislaptop/LaravelFivePackageBridges#9]
Long story short, not a Linux guy but doing a project for work the boss insists has to be on Linux, so you may need to baby me a little on the replies because I really have no clue what I'm doing. Sorry and thanks in advance.

Ive followed the instructions to install the package and made the appropriate changes to the files listed, but afterwards when I try to run Sentry I get this error: PHP Fatal error:  Class 'Morrislaptop\LaravelFivePackageBridges\Application' not found in /home/tmcs/snipeit/bootstrap/app.php on line 14

Any Ideas?

**Comment by morrislaptop** [comment]
Are you using the composer autoloader?

**Comment by googledrummer** [comment]
No, I dont believe so.

**Comment by morrislaptop** [comment]
Well there you go ;) You need to use an autoloader compatible with PSR-4
